### ISSUE TITLE
Gas price multi geth

### ISSUE THREAD

**Issue by djsmoke2018** [ethoxy/multi-geth#10]
hello i have the problem that i found a block at ethereum-classic. only that doesn't unlock it. get the error message.

2018/08/24 22:18:29 Failed to unlock blocks: Error while fetching TX receipt: malformed used gas: 0x5208
2018/08/24 22:18:29 Unlocking suspended due to last critical error: Error while fetching TX receipt: malformed used gas: 0x5208

this error message is due to multi-geth

#### System information

Geth version: `multi-geth v1.8.13`
OS & Version: Linux

**Comment by sorpaas** [comment]
@djsmoke2018 Is this issue solved?

If not, can you also tell me what version of open-ethereum-pool are you using?

**Comment by djsmoke2018** [comment]
yes is solved. but I have another problem. I use open-ethereumclassic-pool

Failed to send payment to xxxxxetcwallet, 1295570268 Shannon: invalid argument 0: json: cannot unmarshal hex number with leading zero digits into Go struct field SendTxArgs.value of type *hexutil.Big. Check outgoing tx for xxxxetc wallet

**Comment by Devkon69** [comment]
sorry djsmoke how you solved ?? what version of parity geth sould i use??
