### ISSUE TITLE
testing: regression test against historical chaindata

### ISSUE THREAD

**Issue by whilei** [ethoxy/multi-geth#32]
This was an idea raised by @realcodywburns once upon a time. Would be nice to implement. I believe you could just use `geth [import|export]`. 

This could potentially be used as a part of the CI test suite as well.

**Comment by meowsbits** [comment]
Removing from tracker here b/c it is unlikely to be implemented at scale as an "out of the box" feature or test w/ this repo.

With that said, though, the idea is definitely a valuable one, and is being pursued by etclabscore as a a standalone project/repo that will be made public when ready.
